# Generated by Django 4.1.9 on 2023-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
